In [84]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

GOAL: 
I want to see if global oil prices have a direct impact on Alberta oil sands production. This is particularly interesting because oil sands companies sell oil at a discount on the global market

DATA SOURCE:
Data is being extracted from a CSV from FRED (Federal Reserve Bank of St. Louis) and a CSV from the Government of Alberta

Data Loading

In [85]:
#DCOILWTICO means Daily Crude Oil Prices: West Texas Intermediate (WTI)
data = pd.read_csv("data/DCOILWTICO.csv")

In [86]:
data.head()

  observation_date  DCOILWTICO
0       1986-01-02       25.56
1       1986-01-03       26.00
2       1986-01-06       26.53
3       1986-01-07       25.85
4       1986-01-08       25.87

In [87]:
data.shape

(10513, 2)

Our data is already pretty clean. Dates are in ascending order and the prices are in a numeric style (float).

In [88]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10513 entries, 0 to 10512
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   observation_date  10513 non-null  object
 1   DCOILWTICO        10143 non-null  float64
dtypes: float64(1), object(1)
memory usage: 164.4+ KB

In [89]:
data.columns = ["date", "price"]
data["date"] = pd.to_datetime(data["date"])
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10513 entries, 0 to 10512
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    10513 non-null  datetime64[ns]
 1   price   10143 non-null  float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 164.4 KB

Data exploration

In [90]:
data.isnull().sum()

date       0
price    370
dtype: int64

In [91]:
#If a data point is missing, take on the value of the previous day's
data["price"] = data["price"].ffill().bfill()

In [92]:
data.isnull().sum()

date     0
price    0
dtype: int64

In [93]:
data.head()

        date  price
0 1986-01-02  25.56
1 1986-01-03  26.00
2 1986-01-06  26.53
3 1986-01-07  25.85
4 1986-01-08  25.87

In [94]:
data.describe()

                                date         price
count                          10513  10513.000000
mean   2006-02-24 19:11:56.712641536     48.326903
min              1986-01-02 00:00:00    -36.980000
25%              1996-01-30 00:00:00     20.340000
50%              2006-02-24 00:00:00     43.210000
75%              2016-03-23 00:00:00     71.280000
max              2026-04-20 00:00:00    145.310000
std                              NaN     29.448196

In [95]:
data.to_csv("data/wti_cleaned.csv", index=False)

In [96]:
#The cleaned table still had some missing fields, manually check said fields
data.loc[33]

date     1986-02-18 00:00:00
price                   14.7
Name: 33, dtype: object